---
abstract: 'Perl extension for OpenSSL EC (Elliptic Curves) library'
author:
  - 'Mike McCauley <mikem@airspayce.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-OpenSSL-EC
no_index:
  directory:
    - t
    - inc
requires:
  Crypt::OpenSSL::Bignum: 0.04
version: 0.4
